baseURL = "https://thenowhere.club"
title = "thenowhere.club"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; 2022 thenowhere.club"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    title = "categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = ""      # Your meta description of the site
  header_title = ""
  header_subtitle = ""
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#000000"
    fontColor = "#FFFFFF"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/vigah"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/vigah"
  [[params.social]]
    fa_icon = "fas fa-key fa-1x"
    href = "https://keybase.io/vigah"